var username;
var myName = "M.Huzaifa Shahid";
var message = "Hello World!";
alert(message);
var studentName = "Ali";
var studentAge = 15;
var studentCourse = "Mobile Application Development";
alert(studentName,);
alert(studentAge);
alert(studentCourse);
var pizza = "PIZZA \nPIZZ \nPIZ \nPI \nP";
alert(pizza);  
var email = "huzaifashahid5153@gmail.com";
alert(`My email address is ${email}`);
var book = "A smarter way to learn JavaScript";
alert(`I am trying to learn from the Book ${book}`);
var html = "Yah! I can write HTML content through Javascript";
document.write(html);
var char = "-----&*$*&-----";
alert(char);
